package admin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

import dao.DatabaseUtil;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JOptionPane;
import main.QAPanel;
import util.PDFGenerator;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kr
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    private List<String> quotes; // List to hold quotes
    private Random random; // Random object for generating random indices
    
    public AdminDashboard() {
        initComponents();
        showBarChart();

//          displayRandomQuote(); 
    }
    
//    private void displayRandomQuote() {
//        int index = random.nextInt(quotes.size());
//        String quote = quotes.get(index);
//        jLabel4.setText(quote);
//    }
    
   
    
       public void showBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(1.5, "Rating", "Mr. Smith");
        dataset.setValue(3.2, "Rating", "Ms. Johnson");
        dataset.setValue(2.8, "Rating", "Mr. Williams");
        dataset.setValue(4.0, "Rating", "Ms. Brown");
        dataset.setValue(3.3, "Rating", "Mr. Jones");

        JFreeChart chart = ChartFactory.createBarChart(
                "Top Teacher Ratings",
                "Teacher",
                "Rating",
                dataset,
                PlotOrientation.HORIZONTAL,
                false, true, false
        );

        CategoryPlot categoryPlot = chart.getCategoryPlot();
        categoryPlot.setBackgroundPaint(Color.WHITE);

        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        renderer.setSeriesPaint(0, new Color(254, 193, 6)); // Green color for the bars

        ChartPanel chartPanel = new ChartPanel(chart);
        this.barPanel.removeAll();
        this.barPanel.add(chartPanel, BorderLayout.CENTER);
        this.barPanel.validate();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qaLabel = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        barPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        quotePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quotePanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        quotePanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kist 1.png"))); // NOI18N
        jLabel10.setText("Logo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        logoutLabel.setBackground(new java.awt.Color(0, 0, 0));
        logoutLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log-out.png"))); // NOI18N
        logoutLabel.setText("  Logout");
        jPanel1.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 180, 40));

        jPanel2.setBackground(new java.awt.Color(194, 194, 194));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profile-user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 70));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel1.setText("Admin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 270));

        qaLabel.setBackground(new java.awt.Color(0, 0, 0));
        qaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        qaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/adduser32.png"))); // NOI18N
        qaLabel.setText("Add User");
        qaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qaLabelMouseClicked(evt);
            }
        });
        jPanel1.add(qaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 60));

        settingLabel.setBackground(new java.awt.Color(0, 0, 0));
        settingLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/viewuser.png"))); // NOI18N
        settingLabel.setText("View User");
        settingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingLabelMouseClicked(evt);
            }
        });
        jPanel1.add(settingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 180, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        dashboardLabel.setBackground(new java.awt.Color(0, 0, 0));
        dashboardLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        dashboardLabel.setText("  Dashboard");
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseClicked(evt);
            }
        });
        jPanel6.add(dashboardLabel);
        dashboardLabel.setBounds(10, 10, 180, 30);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barPanel.setBackground(new java.awt.Color(209, 232, 254));
        barPanel.setLayout(new java.awt.BorderLayout());
        jPanel3.add(barPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 500, 340));

        jPanel5.setBackground(new java.awt.Color(209, 232, 254));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(209, 232, 254));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jButton1.setText("Q&A data");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(246, 138, 30), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 40));

        jLabel9.setBackground(new java.awt.Color(30, 63, 168));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 63, 168));
        jLabel9.setText("Download Reports");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 240, 50));

        jButton2.setBackground(new java.awt.Color(209, 232, 254));
        jButton2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jButton2.setText("Rating data");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(246, 138, 30), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 330, 250));

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Dashboard");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        quotePanel.setBackground(new java.awt.Color(209, 232, 254));
        quotePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(30, 63, 168));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 63, 168));
        jLabel8.setText("820");
        quotePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 50));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 138, 30));
        jLabel7.setText("Total Number of Students");
        quotePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 50));

        jPanel3.add(quotePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 290, 160));

        quotePanel1.setBackground(new java.awt.Color(209, 232, 254));
        quotePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(246, 138, 30));
        jLabel14.setText("Programmes");
        quotePanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        jLabel15.setBackground(new java.awt.Color(30, 63, 168));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 63, 168));
        jLabel15.setText("9");
        quotePanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 50));

        jPanel3.add(quotePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 200, 160));

        quotePanel2.setBackground(new java.awt.Color(209, 232, 254));
        quotePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(30, 63, 168));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 63, 168));
        jLabel12.setText("25");
        quotePanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 50));

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(246, 138, 30));
        jLabel13.setText("Total Number of Teachers");
        quotePanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 50));

        jPanel3.add(quotePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 270, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 800));

        setSize(new java.awt.Dimension(1214, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardLabelMouseClicked

    private void qaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qaLabelMouseClicked
        // TODO add your handling code here:
        new AddUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_qaLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        int a = JOptionPane.showMes
     int a = JOptionPane.showConfirmDialog(null, "Do you want to download Q&A data?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0){
          String dest = System.getProperty("user.home") + "/Downloads/qa_data.pdf";
    
    // Generate the PDF
        MySQLPDFGenerator.generatePDF(dest);
    
    // Show success message with the file path
    JOptionPane.showMessageDialog(null, "PDF generated: " + dest);
     }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void settingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingLabelMouseClicked
        // TODO add your handling code here:
        new ViewUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingLabelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to download Rating data?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0){
           String dest = System.getProperty("user.home") + "/Downloads/rating_data.pdf";
    
    // Generate the PDF
       RatingPDFGenerator.generatePDF(dest);
    
    // Show success message with the file path
    JOptionPane.showMessageDialog(null, "PDF generated: " + dest);
     }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminDashboard studentDashboard = new AdminDashboard();
                studentDashboard.setVisible(true);
//                  Dashboard.setLocationRelativeTo(null);
//                new AdminDashboard().setVisible(true);
//                new AdminDashboard().setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barPanel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel qaLabel;
    private javax.swing.JPanel quotePanel;
    private javax.swing.JPanel quotePanel1;
    private javax.swing.JPanel quotePanel2;
    private javax.swing.JLabel settingLabel;
    // End of variables declaration//GEN-END:variables
}
