package main;

import main.StudentDashboard;
import questions.QAone;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kr
 */
public class QAPanel extends javax.swing.JFrame {

    /**
     * Creates new form QAPanel
     */
  
    public QAPanel() {
        initComponents();
        setLocationRelativeTo(null);
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qaLabel = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        teacher6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        teacher4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teacher5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        teacher1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teacher2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teacher3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kist 1.png"))); // NOI18N
        jLabel10.setText("Logo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        logoutLabel.setBackground(new java.awt.Color(0, 0, 0));
        logoutLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log-out.png"))); // NOI18N
        logoutLabel.setText("  Logout");
        jPanel1.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 180, 40));

        jPanel2.setBackground(new java.awt.Color(194, 194, 194));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profile-user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 70));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel1.setText("Student");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 270));

        qaLabel.setBackground(new java.awt.Color(0, 0, 0));
        qaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        qaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/qa.png"))); // NOI18N
        qaLabel.setText("  Q&A");
        qaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qaLabelMouseClicked(evt);
            }
        });
        jPanel1.add(qaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 180, -1));

        settingLabel.setBackground(new java.awt.Color(0, 0, 0));
        settingLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rating.png"))); // NOI18N
        settingLabel.setText("  Ratings");
        settingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingLabelMouseClicked(evt);
            }
        });
        jPanel1.add(settingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 180, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 230, 50));

        dashboardLabel.setBackground(new java.awt.Color(0, 0, 0));
        dashboardLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        dashboardLabel.setText("  Dashboard");
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseClicked(evt);
            }
        });
        jPanel1.add(dashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Q&A");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        teacher6.setBackground(new java.awt.Color(209, 232, 254));
        teacher6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher6MouseClicked(evt);
            }
        });
        teacher6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher6.png"))); // NOI18N
        teacher6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel25.setBackground(new java.awt.Color(246, 138, 30));
        jLabel25.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(30, 63, 138));
        jLabel25.setText("(4.9)Lebron Shrestha");
        teacher6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jPanel3.add(teacher6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 220, 250));

        teacher4.setBackground(new java.awt.Color(209, 232, 254));
        teacher4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher4MouseClicked(evt);
            }
        });
        teacher4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher4.png"))); // NOI18N
        teacher4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel23.setBackground(new java.awt.Color(246, 138, 30));
        jLabel23.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(30, 63, 138));
        jLabel23.setText("(4.5) Hari Chapagain");
        teacher4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 30));

        jPanel3.add(teacher4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 220, 250));

        teacher5.setBackground(new java.awt.Color(209, 232, 254));
        teacher5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher5MouseClicked(evt);
            }
        });
        teacher5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/techer5.png"))); // NOI18N
        teacher5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel24.setBackground(new java.awt.Color(246, 138, 30));
        jLabel24.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(30, 63, 138));
        jLabel24.setText("(4.8)Bimal Pakhrin");
        teacher5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 30));

        jPanel3.add(teacher5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 220, 250));

        teacher1.setBackground(new java.awt.Color(209, 232, 254));
        teacher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher1MouseClicked(evt);
            }
        });
        teacher1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher1.png"))); // NOI18N
        teacher1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel16.setBackground(new java.awt.Color(246, 138, 30));
        jLabel16.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 63, 138));
        jLabel16.setText("(4.6) Riya Sharma");
        teacher1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 208, 180, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jPanel3.add(teacher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, 250));

        teacher2.setBackground(new java.awt.Color(209, 232, 254));
        teacher2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher2MouseClicked(evt);
            }
        });
        teacher2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher2.png"))); // NOI18N
        teacher2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel21.setBackground(new java.awt.Color(246, 138, 30));
        jLabel21.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 63, 138));
        jLabel21.setText("(4.7) Isha Rai");
        teacher2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 208, 150, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jPanel3.add(teacher2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 220, 250));

        teacher3.setBackground(new java.awt.Color(209, 232, 254));
        teacher3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher3MouseClicked(evt);
            }
        });
        teacher3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher3.png"))); // NOI18N
        teacher3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 210));

        jLabel22.setBackground(new java.awt.Color(246, 138, 30));
        jLabel22.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(30, 63, 138));
        jLabel22.setText("(4.3) Ram Kumar");
        teacher3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star24px.png"))); // NOI18N
        teacher3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 30));

        jPanel3.add(teacher3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 220, 250));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qaLabelMouseClicked
        // TODO add your handling code here:
        new QAPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_qaLabelMouseClicked

    private void dashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardLabelMouseClicked

    private void teacher6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher6MouseClicked
        // TODO add your handling code here:
        new QAone("Lebron Shrestha").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacher6MouseClicked

    private void teacher4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher4MouseClicked
        // TODO add your handling code here:
        new QAone("hari Chapagain").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacher4MouseClicked

    private void teacher5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher5MouseClicked
        // TODO add your handling code here:
        new QAone("Bimal Pakhrin").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacher5MouseClicked

    private void teacher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher1MouseClicked
        new QAone("Riya Sharma").setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_teacher1MouseClicked

    private void teacher2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher2MouseClicked
        // TODO add your handling code here:
        new QAone("Isha Rai").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacher2MouseClicked

    private void teacher3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher3MouseClicked
        // TODO add your handling code here:
        new QAone("Ram Kumar").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacher3MouseClicked

    private void settingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingLabelMouseClicked
        // TODO add your handling code here:
        new RatingPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QAPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QAPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QAPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QAPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new QAPanel().setVisible(true);
//                new QAPanel().setLocationRelativeTo(null);
//                QAPanel QAPanel = new QAPanel();
                new QAPanel().setVisible(true);
//                QAPanel.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel qaLabel;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JPanel teacher1;
    private javax.swing.JPanel teacher2;
    private javax.swing.JPanel teacher3;
    private javax.swing.JPanel teacher4;
    private javax.swing.JPanel teacher5;
    private javax.swing.JPanel teacher6;
    // End of variables declaration//GEN-END:variables
}
