/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import surveyform.SurveyForm;

/**
 *
 * @author kr
 */
public class ReviewPanel extends javax.swing.JFrame {

    /**
     * Creates new form ReviewPanel
     */
    public ReviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dashboardLabel = new javax.swing.JLabel();
        qaLabel = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        reviewLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        strongdisagree = new javax.swing.JRadioButton();
        strongagree = new javax.swing.JRadioButton();
        agree = new javax.swing.JRadioButton();
        middle = new javax.swing.JRadioButton();
        disagree = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        strongdisagree1 = new javax.swing.JRadioButton();
        strongagree1 = new javax.swing.JRadioButton();
        agree1 = new javax.swing.JRadioButton();
        middle1 = new javax.swing.JRadioButton();
        disagree1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        strongdisagree2 = new javax.swing.JRadioButton();
        strongagree2 = new javax.swing.JRadioButton();
        agree2 = new javax.swing.JRadioButton();
        middle2 = new javax.swing.JRadioButton();
        disagree2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        strongdisagree3 = new javax.swing.JRadioButton();
        strongagree3 = new javax.swing.JRadioButton();
        agree3 = new javax.swing.JRadioButton();
        middle3 = new javax.swing.JRadioButton();
        disagree3 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        strongdisagree4 = new javax.swing.JRadioButton();
        strongagree4 = new javax.swing.JRadioButton();
        agree4 = new javax.swing.JRadioButton();
        middle4 = new javax.swing.JRadioButton();
        disagree4 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        strongdisagree5 = new javax.swing.JRadioButton();
        strongagree5 = new javax.swing.JRadioButton();
        agree5 = new javax.swing.JRadioButton();
        middle5 = new javax.swing.JRadioButton();
        disagree5 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        strongdisagree6 = new javax.swing.JRadioButton();
        strongagree6 = new javax.swing.JRadioButton();
        agree6 = new javax.swing.JRadioButton();
        middle6 = new javax.swing.JRadioButton();
        disagree6 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        strongdisagree7 = new javax.swing.JRadioButton();
        strongagree7 = new javax.swing.JRadioButton();
        agree7 = new javax.swing.JRadioButton();
        middle7 = new javax.swing.JRadioButton();
        disagree7 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        strongdisagree8 = new javax.swing.JRadioButton();
        strongagree8 = new javax.swing.JRadioButton();
        agree8 = new javax.swing.JRadioButton();
        middle8 = new javax.swing.JRadioButton();
        disagree8 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        strongdisagree9 = new javax.swing.JRadioButton();
        strongagree9 = new javax.swing.JRadioButton();
        agree9 = new javax.swing.JRadioButton();
        middle9 = new javax.swing.JRadioButton();
        disagree9 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kist 1.png"))); // NOI18N
        jLabel10.setText("Logo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        logoutLabel.setBackground(new java.awt.Color(0, 0, 0));
        logoutLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log-out.png"))); // NOI18N
        logoutLabel.setText("  Logout");
        jPanel1.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 180, 40));

        jPanel2.setBackground(new java.awt.Color(194, 194, 194));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profile-user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 70));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 25)); // NOI18N
        jLabel1.setText("Student");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 270));

        dashboardLabel.setBackground(new java.awt.Color(0, 0, 0));
        dashboardLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        dashboardLabel.setText("  Dashboard");
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseClicked(evt);
            }
        });
        jPanel1.add(dashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 180, -1));

        qaLabel.setBackground(new java.awt.Color(0, 0, 0));
        qaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        qaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/qa.png"))); // NOI18N
        qaLabel.setText("  Q&A");
        qaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qaLabelMouseClicked(evt);
            }
        });
        jPanel1.add(qaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 180, -1));

        settingLabel.setBackground(new java.awt.Color(0, 0, 0));
        settingLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settings.png"))); // NOI18N
        settingLabel.setText("  Settings");
        jPanel1.add(settingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 180, 40));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(null);

        reviewLabel.setBackground(new java.awt.Color(0, 0, 0));
        reviewLabel.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        reviewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/review.png"))); // NOI18N
        reviewLabel.setText("  Review");
        jPanel15.add(reviewLabel);
        reviewLabel.setBounds(10, 10, 180, 34);

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 840));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Review");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 20, -1, -1));

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Strongly disagree");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagreeActionPerformed(evt);
            }
        });
        jPanel4.add(strongdisagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagreeActionPerformed(evt);
            }
        });
        jPanel4.add(strongagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeActionPerformed(evt);
            }
        });
        jPanel4.add(agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleActionPerformed(evt);
            }
        });
        jPanel4.add(middle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagreeActionPerformed(evt);
            }
        });
        jPanel4.add(disagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setText("The Teacher explains concepts clearly.");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Strongly agree");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 670, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Strongly disagree");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree1ActionPerformed(evt);
            }
        });
        jPanel5.add(strongdisagree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree1ActionPerformed(evt);
            }
        });
        jPanel5.add(strongagree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree1ActionPerformed(evt);
            }
        });
        jPanel5.add(agree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle1ActionPerformed(evt);
            }
        });
        jPanel5.add(middle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree1ActionPerformed(evt);
            }
        });
        jPanel5.add(disagree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel8.setText("The teacher respects different cultures and backgrounds.");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Strongly agree");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 670, 80));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Strongly disagree");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree2ActionPerformed(evt);
            }
        });
        jPanel7.add(strongdisagree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree2ActionPerformed(evt);
            }
        });
        jPanel7.add(strongagree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree2ActionPerformed(evt);
            }
        });
        jPanel7.add(agree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle2ActionPerformed(evt);
            }
        });
        jPanel7.add(middle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree2ActionPerformed(evt);
            }
        });
        jPanel7.add(disagree2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel12.setText("The Teacher makes the class interesting.");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Strongly agree");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 670, 80));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Strongly disagree");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree3ActionPerformed(evt);
            }
        });
        jPanel8.add(strongdisagree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree3ActionPerformed(evt);
            }
        });
        jPanel8.add(strongagree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree3ActionPerformed(evt);
            }
        });
        jPanel8.add(agree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle3ActionPerformed(evt);
            }
        });
        jPanel8.add(middle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree3ActionPerformed(evt);
            }
        });
        jPanel8.add(disagree3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel15.setText("The teacher is approachable for questions and help.");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Strongly agree");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 670, 80));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("Strongly disagree");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree4ActionPerformed(evt);
            }
        });
        jPanel9.add(strongdisagree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree4ActionPerformed(evt);
            }
        });
        jPanel9.add(strongagree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree4ActionPerformed(evt);
            }
        });
        jPanel9.add(agree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle4ActionPerformed(evt);
            }
        });
        jPanel9.add(middle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree4ActionPerformed(evt);
            }
        });
        jPanel9.add(disagree4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel18.setText("The teacher communicates expectations and instructions clearly.");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setText("Strongly agree");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 670, 80));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("Strongly disagree");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree5ActionPerformed(evt);
            }
        });
        jPanel10.add(strongdisagree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree5ActionPerformed(evt);
            }
        });
        jPanel10.add(strongagree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree5ActionPerformed(evt);
            }
        });
        jPanel10.add(agree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle5ActionPerformed(evt);
            }
        });
        jPanel10.add(middle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree5ActionPerformed(evt);
            }
        });
        jPanel10.add(disagree5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel21.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel21.setText("The teacher provides timely and constructive feedback.");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setText("Strongly agree");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 670, 80));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("Strongly disagree");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree6ActionPerformed(evt);
            }
        });
        jPanel11.add(strongdisagree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree6ActionPerformed(evt);
            }
        });
        jPanel11.add(strongagree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree6ActionPerformed(evt);
            }
        });
        jPanel11.add(agree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle6ActionPerformed(evt);
            }
        });
        jPanel11.add(middle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree6ActionPerformed(evt);
            }
        });
        jPanel11.add(disagree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel24.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel24.setText("The teacher uses a variety of teaching methods effectively.");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setText("Strongly agree");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 670, 80));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 51));
        jLabel26.setText("Strongly disagree");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree7ActionPerformed(evt);
            }
        });
        jPanel12.add(strongdisagree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree7ActionPerformed(evt);
            }
        });
        jPanel12.add(strongagree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree7ActionPerformed(evt);
            }
        });
        jPanel12.add(agree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle7ActionPerformed(evt);
            }
        });
        jPanel12.add(middle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree7ActionPerformed(evt);
            }
        });
        jPanel12.add(disagree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel27.setText("The course materials are relevant and up-to-date.");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 0));
        jLabel28.setText("Strongly agree");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 670, 80));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("Strongly disagree");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree8ActionPerformed(evt);
            }
        });
        jPanel13.add(strongdisagree8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree8ActionPerformed(evt);
            }
        });
        jPanel13.add(strongagree8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree8ActionPerformed(evt);
            }
        });
        jPanel13.add(agree8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle8ActionPerformed(evt);
            }
        });
        jPanel13.add(middle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree8ActionPerformed(evt);
            }
        });
        jPanel13.add(disagree8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel30.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel30.setText("The teacher encourages class participation and questions.");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel31.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 0));
        jLabel31.setText("Strongly agree");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 670, 80));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 51, 51));
        jLabel32.setText("Strongly disagree");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 150, -1));

        strongdisagree9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongdisagree9ActionPerformed(evt);
            }
        });
        jPanel14.add(strongdisagree9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        strongagree9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongagree9ActionPerformed(evt);
            }
        });
        jPanel14.add(strongagree9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        agree9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agree9ActionPerformed(evt);
            }
        });
        jPanel14.add(agree9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        middle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle9ActionPerformed(evt);
            }
        });
        jPanel14.add(middle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        disagree9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disagree9ActionPerformed(evt);
            }
        });
        jPanel14.add(disagree9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel33.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel33.setText("The teacher uses technology effectively in lessons.");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel34.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 0));
        jLabel34.setText("Strongly agree");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, -1));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 670, 80));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 710, 830));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardLabelMouseClicked

    private void qaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qaLabelMouseClicked
        // TODO add your handling code here:
        new QAPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_qaLabelMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        new SurveyForm().setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void strongdisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagreeActionPerformed

    private void strongagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagreeActionPerformed

    private void agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreeActionPerformed

    private void middleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleActionPerformed

    private void disagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagreeActionPerformed

    private void strongdisagree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree1ActionPerformed

    private void strongagree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree1ActionPerformed

    private void agree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree1ActionPerformed

    private void middle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle1ActionPerformed

    private void disagree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree1ActionPerformed

    private void strongdisagree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree2ActionPerformed

    private void strongagree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree2ActionPerformed

    private void agree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree2ActionPerformed

    private void middle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle2ActionPerformed

    private void disagree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree2ActionPerformed

    private void strongdisagree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree3ActionPerformed

    private void strongagree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree3ActionPerformed

    private void agree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree3ActionPerformed

    private void middle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle3ActionPerformed

    private void disagree3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree3ActionPerformed

    private void strongdisagree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree4ActionPerformed

    private void strongagree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree4ActionPerformed

    private void agree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree4ActionPerformed

    private void middle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle4ActionPerformed

    private void disagree4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree4ActionPerformed

    private void strongdisagree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree5ActionPerformed

    private void strongagree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree5ActionPerformed

    private void agree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree5ActionPerformed

    private void middle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle5ActionPerformed

    private void disagree5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree5ActionPerformed

    private void strongdisagree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree6ActionPerformed

    private void strongagree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree6ActionPerformed

    private void agree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree6ActionPerformed

    private void middle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle6ActionPerformed

    private void disagree6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree6ActionPerformed

    private void strongdisagree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree7ActionPerformed

    private void strongagree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree7ActionPerformed

    private void agree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree7ActionPerformed

    private void middle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle7ActionPerformed

    private void disagree7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree7ActionPerformed

    private void strongdisagree8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree8ActionPerformed

    private void strongagree8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree8ActionPerformed

    private void agree8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree8ActionPerformed

    private void middle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle8ActionPerformed

    private void disagree8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree8ActionPerformed

    private void strongdisagree9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongdisagree9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongdisagree9ActionPerformed

    private void strongagree9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongagree9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strongagree9ActionPerformed

    private void agree9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agree9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agree9ActionPerformed

    private void middle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middle9ActionPerformed

    private void disagree9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disagree9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disagree9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agree;
    private javax.swing.JRadioButton agree1;
    private javax.swing.JRadioButton agree2;
    private javax.swing.JRadioButton agree3;
    private javax.swing.JRadioButton agree4;
    private javax.swing.JRadioButton agree5;
    private javax.swing.JRadioButton agree6;
    private javax.swing.JRadioButton agree7;
    private javax.swing.JRadioButton agree8;
    private javax.swing.JRadioButton agree9;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JRadioButton disagree;
    private javax.swing.JRadioButton disagree1;
    private javax.swing.JRadioButton disagree2;
    private javax.swing.JRadioButton disagree3;
    private javax.swing.JRadioButton disagree4;
    private javax.swing.JRadioButton disagree5;
    private javax.swing.JRadioButton disagree6;
    private javax.swing.JRadioButton disagree7;
    private javax.swing.JRadioButton disagree8;
    private javax.swing.JRadioButton disagree9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JRadioButton middle;
    private javax.swing.JRadioButton middle1;
    private javax.swing.JRadioButton middle2;
    private javax.swing.JRadioButton middle3;
    private javax.swing.JRadioButton middle4;
    private javax.swing.JRadioButton middle5;
    private javax.swing.JRadioButton middle6;
    private javax.swing.JRadioButton middle7;
    private javax.swing.JRadioButton middle8;
    private javax.swing.JRadioButton middle9;
    private javax.swing.JLabel qaLabel;
    private javax.swing.JLabel reviewLabel;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JRadioButton strongagree;
    private javax.swing.JRadioButton strongagree1;
    private javax.swing.JRadioButton strongagree2;
    private javax.swing.JRadioButton strongagree3;
    private javax.swing.JRadioButton strongagree4;
    private javax.swing.JRadioButton strongagree5;
    private javax.swing.JRadioButton strongagree6;
    private javax.swing.JRadioButton strongagree7;
    private javax.swing.JRadioButton strongagree8;
    private javax.swing.JRadioButton strongagree9;
    private javax.swing.JRadioButton strongdisagree;
    private javax.swing.JRadioButton strongdisagree1;
    private javax.swing.JRadioButton strongdisagree2;
    private javax.swing.JRadioButton strongdisagree3;
    private javax.swing.JRadioButton strongdisagree4;
    private javax.swing.JRadioButton strongdisagree5;
    private javax.swing.JRadioButton strongdisagree6;
    private javax.swing.JRadioButton strongdisagree7;
    private javax.swing.JRadioButton strongdisagree8;
    private javax.swing.JRadioButton strongdisagree9;
    // End of variables declaration//GEN-END:variables
}
